### ISSUE TITLE
obs使用whip协议推流无声

### ISSUE THREAD

**Issue by BySlin** [Monibuca/plugin-webrtc#24]
使用自带预览功能，只有画面没有声音
config.yaml
```
llhls:
  enable: false
hls:
  enable: false
monitor:
  enable: false
webrtc:
  iceservers: []
  publicip: [] # 可以是数组也可以是字符串（内部自动转成数组）
  port: udp:9000 # 可以是udp:8000-9000 范围端口，也可以udp:9000 单个端口
  pli: 2s # 2s
```

obs 配置
<img width="747" alt="1689519861147" src="https://github.com/Monibuca/plugin-webrtc/assets/16970823/52ceadd5-80c6-4983-9aab-662821da2649">
<img width="733" alt="1689519886272" src="https://github.com/Monibuca/plugin-webrtc/assets/16970823/baf99aef-d008-4e99-8679-19ccf12e346a">
